const fields=['role','task','context','audience','constraints','format'];
const modes=['Text','Image','Video','Coding'];
const cookieName='__Host-pm-session',flowName='__Host-pm-flow';
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
const random=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
const cookie=(name,value,seconds)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${seconds}`;
const cookies=r=>Object.fromEntries((r.headers.get('Cookie')||'').split(';').map(x=>x.trim().split('=')));
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
const encode=s=>{const bytes=new TextEncoder().encode(s);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)};
const decode=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
const configured=e=>e.SESSIONS&&e.GITHUB_CLIENT_ID&&e.GITHUB_CLIENT_SECRET&&e.ALLOWED_LOGIN&&e.REPO_OWNER&&e.REPO_NAME&&e.PUBLIC_ORIGIN&&e.TOKEN_ENCRYPTION_KEY&&e.ALLOWED_USER_ID;
const allowed=(login,e)=>login.toLowerCase()===e.ALLOWED_LOGIN.toLowerCase();
async function seal(value,e){const iv=crypto.getRandomValues(new Uint8Array(12));const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(e.TOKEN_ENCRYPTION_KEY),c=>c.charCodeAt(0)),'AES-GCM',false,['encrypt']);const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value));return {iv:btoa(String.fromCharCode(...iv)),data:btoa(String.fromCharCode(...new Uint8Array(encrypted)))}}
async function unseal(value,e){const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(e.TOKEN_ENCRYPTION_KEY),c=>c.charCodeAt(0)),'AES-GCM',false,['decrypt']);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(value.iv),c=>c.charCodeAt(0))},key,Uint8Array.from(atob(value.data),c=>c.charCodeAt(0))))}
async function github(token,path,options={}){const response=await fetch('https://api.github.com'+path,{...options,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'User-Agent':'Prompt-Manufaktur','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...options.headers}});if(!response.ok){if(response.status===404)fail('Requested GitHub resource was not found.',404);if([409,422].includes(response.status))fail('The file changed or already exists. Refresh the library before retrying.',409);if([401,403].includes(response.status))fail('GitHub access was denied. Sign in again or check repository permissions.',403);fail('GitHub is temporarily unavailable.',502)}return response.status===204?null:response.json()}
function repoPath(e){return '/repos/'+encodeURIComponent(e.REPO_OWNER)+'/'+encodeURIComponent(e.REPO_NAME)}
async function checkRepository(token,e){const r=await github(token,repoPath(e));if(!r.private||r.full_name.toLowerCase()!==`${e.REPO_OWNER}/${e.REPO_NAME}`.toLowerCase())fail('Library requires the configured private repository.',403);if(!r.permissions?.push)fail('Write access to the private repository is required.',403);return r}
async function session(r,e,verify=true){const id=cookies(r)[cookieName];if(!id||!/^[a-f0-9]{64}$/.test(id))fail('Sign in with GitHub to open your library.',401);const s=await e.SESSIONS.get('session:'+id,'json');if(!s||s.expires<Date.now()||!allowed(s.login,e))fail('Your session expired. Sign in again.',401);s.token=await unseal(s.token,e);if(verify)await checkRepository(s.token,e);return {id,...s}}
function checkWrite(r,u,s){if(r.headers.get('Origin')!==u.origin||r.headers.get('X-CSRF-Token')!==s.csrf)fail('Request verification failed.',403);if(!r.headers.get('Content-Type')?.startsWith('application/json'))fail('JSON content required.',415)}
async function body(r){const text=await r.text();if(text.length>100000)fail('Prompt is too large.',413);try{return JSON.parse(text)}catch{fail('Invalid JSON.')}}
function cleanPrompt(x){if(!x||typeof x!=='object'||typeof x.title!=='string'||!x.title.trim()||x.title.length>100||!modes.includes(x.mode)||!x.state||typeof x.state!=='object')fail('Provide a name, modality, and prompt fields.');const state={};for(const k of fields){if(x.state[k]!==undefined&&typeof x.state[k]!=='string')fail('Prompt fields must be text.');state[k]=x.state[k]||'';if(state[k].length>15000)fail('Prompt field exceeds 15,000 characters.')}if(!fields.some(k=>state[k].trim()))fail('Prompt content is empty.');if(!Array.isArray(x.tags)||x.tags.length>20||x.tags.some(t=>typeof t!=='string'||t.length>60))fail('Use up to 20 short text tags.');return {title:x.title.trim(),mode:x.mode,tags:x.tags,favourite:x.favourite===true,state,date:new Date().toISOString()}}
function fieldBlock(value){const runs=value.match(/`+/g)||[];const fence='`'.repeat(Math.max(3,...runs.map(x=>x.length+1)));return fence+'text\n'+value+'\n'+fence}
function markdown(x){const {state,...meta}=x;return '---\n'+JSON.stringify(meta)+'\n---\n\n# '+x.title.replace(/[\r\n]/g,' ')+'\n\n'+fields.filter(k=>state[k]).map(k=>'## '+k[0].toUpperCase()+k.slice(1)+'\n\n'+fieldBlock(state[k])).join('\n\n')+'\n'}
function parseMarkdown(content,id,sha){let meta,body;const front=content.match(/^---\r?\n([^\n]+)\r?\n---\r?\n/);if(front){try{meta=JSON.parse(front[1])}catch{fail('Invalid JSON front matter.',422)}body=content.slice(front[0].length).trim()}else{const legacy=content.match(/<!-- prompt-manufaktur:v1 ([A-Za-z0-9+/=]+) -->/);if(!legacy)fail('Missing library front matter.',422);try{meta=JSON.parse(decode(legacy[1]))}catch{fail('Invalid library metadata.',422)}body=content.slice(content.indexOf(legacy[0])+legacy[0].length).replace(/^\s*Modality:[^\n]*\n\s*Tags:[^\n]*\n/,'').trim()}
const state=Object.fromEntries(fields.map(k=>[k,'']));const title=body.match(/^# ([^\n]+)\n/);if(title){meta.title=title[1];body=body.slice(title[0].length).trim()}const headings=[];let fence=null,offset=0;for(const line of body.split('\n')){const fm=line.match(/^(`{3,}|~{3,})(.*)$/);if(fm){if(!fence)fence={char:fm[1][0],length:fm[1].length};else if(fm[1][0]===fence.char&&fm[1].length>=fence.length&&fm[2].trim()==='')fence=null;}else if(!fence){const h=line.match(/^## (Role|Task|Context|Audience|Constraints|Format)\s*$/);if(h)headings.push({key:h[1].toLowerCase(),index:offset,length:line.length})}offset+=line.length+1}
if(headings.length&&body.slice(0,headings[0].index).trim()===''){for(let i=0;i<headings.length;i++){const h=headings[i];let value=body.slice(h.index+h.length,headings[i+1]?.index??body.length).trim();const outer=value.match(/^(`{3,}|~{3,})text\n([\s\S]*)\n\1$/);if(outer)value=outer[2];state[h.key]+=(state[h.key]?'\n\n':'')+value}}else state.task=body;return {...cleanPrompt({...meta,state}),date:meta.date,id,sha}}
function filePath(e,id){if(!/^[a-z0-9-]{8,80}$/.test(id))fail('Invalid prompt identifier.');return repoPath(e)+'/contents/prompts/'+id+'.md'}
function redirect(url,header){return new Response(null,{status:302,headers:{Location:url,'Cache-Control':'no-store',...(header?{'Set-Cookie':header}:{})}})}
export default {async fetch(r,e){const u=new URL(r.url);try{
if(!u.pathname.startsWith('/api/')&&!u.pathname.startsWith('/auth/'))return e.ASSETS.fetch(r);
if(!configured(e))return json({error:'Private library is not configured. Follow PRIVATE-LIBRARY-SETUP.md.',configured:false},503);
if(u.origin!==e.PUBLIC_ORIGIN)fail('Invalid application origin.',403);
if(u.pathname==='/auth/login'&&r.method==='GET'){
const state=random(),verifier=random(),flow=random();const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');await e.SESSIONS.put('flow:'+flow,JSON.stringify({state,verifier}),{expirationTtl:600});const auth=new URL('https://github.com/login/oauth/authorize');Object.entries({client_id:e.GITHUB_CLIENT_ID,redirect_uri:e.PUBLIC_ORIGIN+'/auth/callback',state,code_challenge:challenge,code_challenge_method:'S256'}).forEach(([k,v])=>auth.searchParams.set(k,v));return redirect(auth.href,cookie(flowName,flow,600));}
if(u.pathname==='/auth/callback'&&r.method==='GET'){
const flow=cookies(r)[flowName];if(!flow||!/^[a-f0-9]{64}$/.test(flow))fail('Sign-in session is missing. Start again.',403);const data=await e.SESSIONS.get('flow:'+flow,'json');await e.SESSIONS.delete('flow:'+flow);if(!data||u.searchParams.get('state')!==data.state||!u.searchParams.get('code'))fail('Sign-in verification failed. Start again.',403);
const exchange=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:e.GITHUB_CLIENT_ID,client_secret:e.GITHUB_CLIENT_SECRET,code:u.searchParams.get('code'),redirect_uri:e.PUBLIC_ORIGIN+'/auth/callback',code_verifier:data.verifier})});const result=await exchange.json();if(!exchange.ok||!result.access_token)fail('GitHub sign-in failed. Start again.',403);const user=await github(result.access_token,'/user');if(!allowed(user.login,e)||String(user.id)!==String(e.ALLOWED_USER_ID))fail('This private library is restricted to its owner.',403);await checkRepository(result.access_token,e);const id=random(),csrf=random(),ttl=Math.max(60,Math.min(Number(result.expires_in)||8*3600,8*3600));await e.SESSIONS.put('session:'+id,JSON.stringify({token:await seal(result.access_token,e),login:user.login,csrf,expires:Date.now()+ttl*1000}),{expirationTtl:ttl});const response=redirect(e.PUBLIC_ORIGIN+'/#library');response.headers.append('Set-Cookie',cookie(cookieName,id,ttl));response.headers.append('Set-Cookie',cookie(flowName,'',0));return response;}
const s=await session(r,e,u.pathname!=='/api/logout');
if(u.pathname==='/api/session'&&r.method==='GET')return json({authenticated:true,login:s.login,csrf:s.csrf});
if(u.pathname==='/api/logout'&&r.method==='POST'){checkWrite(r,u,s);await e.SESSIONS.delete('session:'+s.id);return json({ok:true},200,{'Set-Cookie':cookie(cookieName,'',0)})}
if(u.pathname==='/api/prompts'&&r.method==='GET'){let files;try{files=await github(s.token,repoPath(e)+'/contents/prompts')}catch(err){if(err.status===404)return json({prompts:[]});throw err}if(!Array.isArray(files))fail('Library folder is invalid.',422);const metadata=files.filter(x=>x.type==='file'&&/^[a-z0-9-]{8,80}\.md$/.test(x.name));if(metadata.length>300)fail('Library exceeds the 300-prompt listing limit.',413);const prompts=[];for(let i=0;i<metadata.length;i+=8){await Promise.all(metadata.slice(i,i+8).map(async file=>{const f=await github(s.token,filePath(e,file.name.slice(0,-3)));try{prompts.push(parseMarkdown(decode(f.content),file.name.slice(0,-3),f.sha))}catch(err){prompts.push({id:file.name.slice(0,-3),sha:f.sha,title:file.name,invalid:true})}}))}return json({prompts:prompts.sort((a,b)=>(b.date||'').localeCompare(a.date||''))})}
const match=u.pathname.match(/^\/api\/prompts\/([a-z0-9-]{8,80})$/);if(match&&['PUT','DELETE'].includes(r.method)){checkWrite(r,u,s);const input=await body(r),path=filePath(e,match[1]);if(input.sha!==undefined&&(typeof input.sha!=='string'||!/^[a-f0-9]{40,64}$/.test(input.sha)))fail('Invalid file version.');if(r.method==='DELETE'){if(!input.sha)fail('File version required.');await github(s.token,path,{method:'DELETE',body:JSON.stringify({message:'Delete prompt '+match[1],sha:input.sha})});return json({ok:true})}const prompt=cleanPrompt(input);const result=await github(s.token,path,{method:'PUT',body:JSON.stringify({message:(input.sha?'Update':'Create')+' prompt '+match[1],content:encode(markdown(prompt)),...(input.sha?{sha:input.sha}:{})})});return json({...prompt,id:match[1],sha:result.content.sha});}
return json({error:'Route not found.'},404);
}catch(err){return json({error:err.status?err.message:'The library could not complete this request.'},err.status||500)}}};
